INSERT INTO PRODUCT (NAME, PRICE) VALUES ('Chiken', 120);
INSERT INTO PRODUCT (NAME, price) VALUES ('potato', 80);
INSERT INTO  PRODUCT (NAME, PRICE) VALUES ('book', 60);
INSERT INTO PRODUCT (NAME, PRICE) VALUES ('KEY', 600);
INSERT INTO PRODUCT (NAME, PRICE) VALUES ('computer', 18956);